import { ComponentType } from './componentTypes';

export const ComponentTypeOptions = [
	{ label: '输入框', value: ComponentType.INPUT },
	{ label: '下拉选择', value: ComponentType.SELECT },
	{ label: '复选框', value: ComponentType.CHECKBOX },
	{ label: '复选框组', value: ComponentType.CHECKBOX_GROUP },
	{ label: '单选框', value: ComponentType.RADIO },
	{ label: '单选框组', value: ComponentType.RADIO_GROUP },
	{ label: '文本域', value: ComponentType.TEXTAREA },
	{ label: '日期选择器', value: ComponentType.DATE_PICKER },
	{ label: '日期范围选择器', value: ComponentType.DATE_RANGE_PICKER },
	{ label: '时间选择器', value: ComponentType.TIME_PICKER },
	{ label: '容器', value: ComponentType.CONTAINER },
	{ label: '动态表单', value: ComponentType.DYNAMIC_FORM },
	{ label: '自定义组件', value: ComponentType.CUSTOM },
	// 新增表单组件
	{ label: '标签页', value: ComponentType.TAB },
	{ label: '步骤条', value: ComponentType.STEPS },
	{ label: '抽屉', value: ComponentType.DRAWER },
	{ label: '开关', value: ComponentType.SWITCH },
	{ label: '数字输入框', value: ComponentType.INPUT_NUMBER },
	{ label: '滑块', value: ComponentType.SLIDER },
	{ label: '评分', value: ComponentType.RATE },
	{ label: '自动完成', value: ComponentType.AUTO_COMPLETE },
	{ label: '级联选择', value: ComponentType.CASCADER },
	{ label: '穿梭框', value: ComponentType.TRANSFER },
	{ label: '树选择', value: ComponentType.TREE_SELECT },
	// 非表单组件
	{ label: '按钮', value: ComponentType.BUTTON },
	{ label: '图标', value: ComponentType.ICON },
	{ label: '分割线', value: ComponentType.DIVIDER },
	{ label: '警告提示', value: ComponentType.ALERT },
	{ label: '卡片', value: ComponentType.CARD },
	{ label: '标签', value: ComponentType.TAG },
	{ label: '徽标', value: ComponentType.BADGE },
	{ label: '进度条', value: ComponentType.PROGRESS },
	{ label: '加载中', value: ComponentType.SPIN },
	{ label: '空状态', value: ComponentType.EMPTY },
	{ label: '结果页', value: ComponentType.RESULT },
];

// 组件显示名称映射
export const ComponentDisplayNames: Record<ComponentType, string> = {
	[ComponentType.INPUT]: '输入框',
	[ComponentType.SELECT]: '下拉选择',
	[ComponentType.CHECKBOX]: '复选框',
	[ComponentType.CHECKBOX_GROUP]: '复选框组',
	[ComponentType.RADIO]: '单选框',
	[ComponentType.RADIO_GROUP]: '单选框组',
	[ComponentType.TEXTAREA]: '文本域',
	[ComponentType.DATE_PICKER]: '日期选择器',
	[ComponentType.DATE_RANGE_PICKER]: '日期范围选择器',
	[ComponentType.TIME_PICKER]: '时间选择器',
	[ComponentType.CONTAINER]: '容器',
	[ComponentType.DYNAMIC_FORM]: '动态表单',
	[ComponentType.CUSTOM]: '自定义组件',
	// 新增表单组件
	[ComponentType.TAB]: '标签页',
	[ComponentType.STEPS]: '步骤条',
	[ComponentType.DRAWER]: '抽屉',
	[ComponentType.SWITCH]: '开关',
	[ComponentType.INPUT_NUMBER]: '数字输入框',
	[ComponentType.SLIDER]: '滑块',
	[ComponentType.RATE]: '评分',
	[ComponentType.AUTO_COMPLETE]: '自动完成',
	[ComponentType.CASCADER]: '级联选择',
	[ComponentType.TRANSFER]: '穿梭框',
	[ComponentType.TREE_SELECT]: '树选择',
	// 非表单组件
	[ComponentType.BUTTON]: '按钮',
	[ComponentType.ICON]: '图标',
	[ComponentType.DIVIDER]: '分割线',
	[ComponentType.ALERT]: '警告提示',
	[ComponentType.CARD]: '卡片',
	[ComponentType.TAG]: '标签',
	[ComponentType.BADGE]: '徽标',
	[ComponentType.PROGRESS]: '进度条',
	[ComponentType.SPIN]: '加载中',
	[ComponentType.EMPTY]: '空状态',
	[ComponentType.RESULT]: '结果页',
};
