import {
	CheckboxGroupProps,
	TextAreaProps,
	DateRangePickerProps,
	ContainerProps,
	DynamicFormProps,
	TabProps,
	SliderProps,
} from '@easy-page/pc';
import {
	InputProps,
	SelectProps,
	CheckboxProps,
	RadioProps,
	RadioGroupProps,
	DatePickerProps,
	TimePickerProps,
	StepsProps,
	DrawerProps,
	SwitchProps,
	InputNumberProps,
	RateProps,
	AutoCompleteProps,
	CascaderProps,
	TransferProps,
	TreeSelectProps,
	ButtonProps,
	DividerProps,
	AlertProps,
	CardProps,
	TagProps,
	BadgeProps,
	ProgressProps,
	SpinProps,
	EmptyProps,
	ResultProps,
} from 'antd';
import { CustomProps, IconProps } from './componentProps';
import { ComponentType } from './componentTypes';

// 组件属性映射
export const ComponentPropsMap: Record<ComponentType, any> = {
	[ComponentType.INPUT]: {} as InputProps,
	[ComponentType.SELECT]: {} as SelectProps,
	[ComponentType.CHECKBOX]: {} as CheckboxProps,
	[ComponentType.CHECKBOX_GROUP]: {} as CheckboxGroupProps,
	[ComponentType.RADIO]: {} as RadioProps,
	[ComponentType.RADIO_GROUP]: {} as RadioGroupProps,
	[ComponentType.TEXTAREA]: {} as TextAreaProps,
	[ComponentType.DATE_PICKER]: {} as DatePickerProps,
	[ComponentType.DATE_RANGE_PICKER]: {} as DateRangePickerProps,
	[ComponentType.TIME_PICKER]: {} as TimePickerProps,
	[ComponentType.CONTAINER]: {} as ContainerProps,
	[ComponentType.DYNAMIC_FORM]: {} as DynamicFormProps,
	[ComponentType.CUSTOM]: {} as CustomProps,
	// 新增表单组件
	[ComponentType.TAB]: {} as TabProps,
	[ComponentType.STEPS]: {} as StepsProps,
	[ComponentType.DRAWER]: {} as DrawerProps,
	[ComponentType.SWITCH]: {} as SwitchProps,
	[ComponentType.INPUT_NUMBER]: {} as InputNumberProps,
	[ComponentType.SLIDER]: {} as SliderProps,
	[ComponentType.RATE]: {} as RateProps,
	[ComponentType.AUTO_COMPLETE]: {} as AutoCompleteProps,
	[ComponentType.CASCADER]: {} as CascaderProps,
	[ComponentType.TRANSFER]: {} as TransferProps,
	[ComponentType.TREE_SELECT]: {} as TreeSelectProps,
	// 非表单组件
	[ComponentType.BUTTON]: {} as ButtonProps,
	[ComponentType.ICON]: {} as IconProps,
	[ComponentType.DIVIDER]: {} as DividerProps,
	[ComponentType.ALERT]: {} as AlertProps,
	[ComponentType.CARD]: {} as CardProps,
	[ComponentType.TAG]: {} as TagProps,
	[ComponentType.BADGE]: {} as BadgeProps,
	[ComponentType.PROGRESS]: {} as ProgressProps,
	[ComponentType.SPIN]: {} as SpinProps,
	[ComponentType.EMPTY]: {} as EmptyProps,
	[ComponentType.RESULT]: {} as ResultProps,
};
