export enum ComponentType {
	INPUT = 'Input',
	SELECT = 'Select',
	CHECKBOX = 'Checkbox',
	CHECKBOX_GROUP = 'CheckboxGroup',
	RADIO = 'Radio',
	RADIO_GROUP = 'RadioGroup',
	TEXTAREA = 'TextArea',
	DATE_PICKER = 'DatePicker',
	DATE_RANGE_PICKER = 'DateRangePicker',
	TIME_PICKER = 'TimePicker',
	CONTAINER = 'Container',
	DYNAMIC_FORM = 'DynamicForm',
	CUSTOM = 'Custom',
	// 新增表单组件
	TAB = 'Tab',
	STEPS = 'Steps',
	DRAWER = 'Drawer',
	SWITCH = 'Switch',
	INPUT_NUMBER = 'InputNumber',
	SLIDER = 'Slider',
	RATE = 'Rate',
	AUTO_COMPLETE = 'AutoComplete',
	CASCADER = 'Cascader',
	TRANSFER = 'Transfer',
	TREE_SELECT = 'TreeSelect',
	// 非表单组件（直接使用antd）
	BUTTON = 'Button',
	ICON = 'Icon',
	DIVIDER = 'Divider',
	ALERT = 'Alert',
	CARD = 'Card',
	TAG = 'Tag',
	BADGE = 'Badge',
	PROGRESS = 'Progress',
	SPIN = 'Spin',
	EMPTY = 'Empty',
	RESULT = 'Result',
	// 原生 HTML 元素
	DIV = 'div',
	SPAN = 'span',
	P = 'p',
	A = 'a',
	UL = 'ul',
	LI = 'li',
	CANVAS = 'canvas',
	IFRAME = 'iframe',
  // 简单文本组件
  TEXT = 'text',
}
