import * as React from 'react';
import {
	Button,
	Input,
	Select,
	Checkbox,
	Radio,
	DatePicker,
	TimePicker,
	Switch,
	Tag,
	Badge,
	Typography,
	Space,
	Divider,
	Card,
	Alert,
	Modal,
	Drawer,
	Popconfirm,
	Tooltip,
	Dropdown,
	Menu,
	Breadcrumb,
	Steps,
	Tabs,
	Table,
	Form,
	Row,
	Col,
	Spin,
	Progress,
	Rate,
	Slider,
	Upload,
	Transfer,
	Tree,
	Cascader,
	AutoComplete,
	Mentions,
	InputNumber,
} from 'antd';
import {
	PlusOutlined,
	MinusOutlined,
	EditOutlined,
	DeleteOutlined,
	SearchOutlined,
	SettingOutlined,
	UserOutlined,
	HomeOutlined,
	MailOutlined,
	PhoneOutlined,
	CalendarOutlined,
	ClockCircleOutlined,
	CheckCircleOutlined,
	CloseCircleOutlined,
	ExclamationCircleOutlined,
	InfoCircleOutlined,
	WarningOutlined,
	QuestionCircleOutlined,
	EyeOutlined,
	EyeInvisibleOutlined,
	LockOutlined,
	UnlockOutlined,
	KeyOutlined,
	SafetyOutlined,
	StarOutlined,
	HeartOutlined,
	LikeOutlined,
	DislikeOutlined,
	SmileOutlined,
	FrownOutlined,
	MehOutlined,
	CrownOutlined,
	TrophyOutlined,
	FireOutlined,
	ThunderboltOutlined,
	RocketOutlined,
	BulbOutlined,
	ExperimentOutlined,
	BugOutlined,
	ToolOutlined,
	ApiOutlined,
	CodeOutlined,
	DatabaseOutlined,
	CloudOutlined,
	WifiOutlined,
	AudioOutlined,
	VideoCameraOutlined,
	CameraOutlined,
	PictureOutlined,
	FileOutlined,
	FolderOutlined,
	PaperClipOutlined,
	LinkOutlined,
	DownloadOutlined,
	UploadOutlined,
	SyncOutlined,
	ReloadOutlined,
	RedoOutlined,
	UndoOutlined,
	SaveOutlined,
	FileTextOutlined,
	FileImageOutlined,
	FilePdfOutlined,
	FileWordOutlined,
	FileExcelOutlined,
	FilePptOutlined,
	FileZipOutlined,
	FileUnknownOutlined,
	FileMarkdownOutlined,
	FileAddOutlined,
	FileDoneOutlined,
	FileExclamationOutlined,
	FileProtectOutlined,
	FileSearchOutlined,
	FileSyncOutlined,
} from '@ant-design/icons';
import { ComponentMap } from './types';
import { EASY_PAGE_EXTENDED_COMPONENT_MAP } from './easyPageCoreComponentMap';

// 导入组件示例
import {
	componentExamples,
	formComponents,
	nonFormComponents,
	isFormComponent,
} from '../PreviewExamples';

const { Title, Paragraph, Text } = Typography;
const { Option } = Select;
const { TabPane } = Tabs;
const { Step } = Steps;
const { Item } = Menu;

// 默认组件映射表
export const DEFAULT_COMPONENT_MAP: ComponentMap = {
	// Antd 基础组件
	Button,
	Input,
	Select,
	Checkbox,
	Radio,
	DatePicker,
	TimePicker,
	Switch,
	Tag,
	Badge,
	Typography,
	Space,
	Divider,
	Card,
	Alert,
	Modal,
	Drawer,
	Popconfirm,
	Tooltip,
	Dropdown,
	Menu,
	Breadcrumb,
	Steps,
	Tabs,
	Table,
	Form,
	Row,
	Col,
	Spin,
	Progress,
	Rate,
	Slider,
	Upload,
	Transfer,
	Tree,
	Cascader,
	AutoComplete,
	Mentions,
	InputNumber,

	// Easy-Page 组件
	...EASY_PAGE_EXTENDED_COMPONENT_MAP,

	// Typography 子组件
	Title,
	Paragraph,
	Text,

	// Select 子组件
	Option,

	// Tabs 子组件
	TabPane,

	// Steps 子组件
	Step,

	// Menu 子组件
	Item,

	// Breadcrumb 子组件
	BreadcrumbItem: Breadcrumb.Item,

	// Icons
	PlusOutlined,
	MinusOutlined,
	EditOutlined,
	DeleteOutlined,
	SearchOutlined,
	SettingOutlined,
	UserOutlined,
	HomeOutlined,
	MailOutlined,
	PhoneOutlined,
	CalendarOutlined,
	ClockCircleOutlined,
	CheckCircleOutlined,
	CloseCircleOutlined,
	ExclamationCircleOutlined,
	InfoCircleOutlined,
	WarningOutlined,
	QuestionCircleOutlined,
	EyeOutlined,
	EyeInvisibleOutlined,
	LockOutlined,
	UnlockOutlined,
	KeyOutlined,
	SafetyOutlined,
	StarOutlined,
	HeartOutlined,
	LikeOutlined,
	DislikeOutlined,
	SmileOutlined,
	FrownOutlined,
	MehOutlined,
	CrownOutlined,
	TrophyOutlined,
	FireOutlined,
	ThunderboltOutlined,
	RocketOutlined,
	BulbOutlined,
	ExperimentOutlined,
	BugOutlined,
	ToolOutlined,
	ApiOutlined,
	CodeOutlined,
	DatabaseOutlined,
	CloudOutlined,
	WifiOutlined,
	AudioOutlined,
	VideoCameraOutlined,
	CameraOutlined,
	PictureOutlined,
	FileOutlined,
	FolderOutlined,
	PaperClipOutlined,
	LinkOutlined,
	DownloadOutlined,
	UploadOutlined,
	SyncOutlined,
	ReloadOutlined,
	RedoOutlined,
	UndoOutlined,
	SaveOutlined,
	FileTextOutlined,
	FileImageOutlined,
	FilePdfOutlined,
	FileWordOutlined,
	FileExcelOutlined,
	FilePptOutlined,
	FileZipOutlined,
	FileUnknownOutlined,
	FileMarkdownOutlined,
	FileAddOutlined,
	FileDoneOutlined,
	FileExclamationOutlined,
	FileProtectOutlined,
	FileSearchOutlined,
	FileSyncOutlined,
	// 原生 HTML 元素（直接映射）
	div: (props) => {
		return <div {...props} />;
	},
	span: (props) => {
		return <span {...props} />;
	},
	p: (props) => {
		return <p {...props} />;
	},
	a: (props) => {
		return <a {...props} />;
	},
	ul: (props) => {
		return <ul {...props} />;
	},
	li: (props) => {
		return <li {...props} />;
	},
	canvas: (props) => {
		return <canvas {...props} />;
	},
	iframe: (props) => {
		return <iframe {...props} />;
	},
};

// 导出组件示例相关的函数和映射
export {
	componentExamples,
	formComponents,
	nonFormComponents,
	isFormComponent,
};
